### ISSUE TITLE
rm_accent() poderia retornar um dataframe se um input for um objeto desse tipo

### ISSUE THREAD

**Issue by sillasgonzaga** [abjur/abjutils#1]
Bom, como ambos somos BR, não me importei em escrever uma issue em inglês =/

Voltando ao assunto: a função `janitor::clean_names()` recebe como input um objeto do tipo data.frame. Sei que ela e a `rm_accent()` tem objetivos diferentes, mas pensei em como seria legal poder usar a última dentro de um pipeline só:
`
df %>% clean_names() %>% rm_accent()`

**Comment by Athospd** [comment]
Interessante msm deixar num pipeline assim.
Mas acho q um bom meio termo seria deixar bem explícito com função pra cada coisa, por ex:
rm_accent() que recebe e retorna vetor de string.
rm_accent_from_names() que recebe e retorna data.frames.

Oq acha?

**Comment by jtrecenti** [comment]
rm_accent() pode ser um S3, se receber um data.frame, faz o que o sillas disse. Se for um vetor de character, faz o que faz no vetor

**Comment by clente** [comment]
Na minha opinião o ideal seria criar uma `abjutils::clean_names()` que use `abjutils::rm_accent()`. Pra mim isso deixa mais claro o que cada método faz.

Eu acho que fica um pouco inconsistente se `rm_accent()` mudar os nomes das colunas se receber um data frame :/ As funções do `stringr`, por exemplo, não têm esse comportamento.

**Comment by Athospd** [comment]
Uma boa tbm!

No forkliftr fiz uma função tide_names() que faz isso.

https://github.com/Athospd/forkliftr/blob/master/R/utils.R

**Comment by jtrecenti** [comment]
Eu prefiro usar o `janitor` do que reimplementar a solução de arrumar nomes. Pra ficar claro então, ao invés de usar S3 podemos ir para a solução do @Athospd mesmo.

uma opção menos verborrágica seria

`asciify_names()`

e a utilização seria igual à do @sillasgonzaga 

`df %>% clean_names() %>% asciify_names()`

**Comment by jtrecenti** [comment]
Também podemos fazer uma PR ao janitor para add essa opção como parâmetro, pra ficar

`df %>% janitor::clean_names(ascii = TRUE)`

**Comment by azeloc** [comment]
implementei `rm_accent_from_names`, que funciona exatamente como proposto pelo Silas. Vou fechar a issue, mas ressalto que achei essa PR pro janitor é muito boa.
