### ISSUE TITLE
abjutils and purrr 0.3.1

### ISSUE THREAD

**Issue by lionel-** [abjur/abjutils#11]
Hello, I'm preparing the release of purrr 0.3.1 and I see this revdep failure:

https://github.com/tidyverse/purrr/blob/13ea8bfbf52696d12ba0453a241434b64e4a8066/revdep/problems.md

I think you have already fixed this 8 months ago in https://github.com/abjur/abjutils/commit/7452d1bd41b3a422bbc957ca7de432bbca1ee476 but this hasn't been pushed to CRAN yet. I'm planning to release purrr in 2 weeks.

You could do a preemptive fix release, or wait until purrr 0.3.1 is out. With that version, I think you can skip the `unlist()` entirely because `modify("foo", function(...) "bar")` now returns the same type as the input (here a character vector), as it always should have.

**Comment by clente** [comment]
Thank you very much for the heads up @lionel-! I have just submitted a new version of `abjutils` to CRAN, so I'm guessing this won't be a revdep failure any longer. Closing the issue for now.
