### ISSUE TITLE
pvec() fails when output has zero length

### ISSUE THREAD

**Issue by jtrecenti** [abjur/abjutils#12]
Doesn't work:

``` r
f <- function(x) tibble::tibble()
abjutils::pvec(1:4, f)
#> Error: Tibble columns must have consistent lengths, only values of length one are recycled:
#> * Length 0: Columns `return`, `output`
#> * Length 4: Column `id`
```

<sup>Created on 2019-02-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Curiously, this works: 

``` r
f <- function(x) tibble::tibble(a = "a")[-1,]
abjutils::pvec(1:4, f)
#> # A tibble: 4 x 3
#>      id return output          
#>   <int> <chr>  <list>          
#> 1     1 result <tibble [0 × 1]>
#> 2     2 result <tibble [0 × 1]>
#> 3     3 result <tibble [0 × 1]>
#> 4     4 result <tibble [0 × 1]>
```

<sup>Created on 2019-02-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by clente** [comment]
Unfortunately there is no way to cover for all possible objects that have length zero. The solution was to replace those with `NULL` :( If I think of anything better, I'll reopen the issue and replace the fix.
