### ISSUE TITLE
Usage of furrr

### ISSUE THREAD

**Issue by DavisVaughan** [abjur/abjutils#15]
Hi there, I am working on the next version of furrr and your package has come up in my revdeps as having an issue.

The warning that I get is:

```r
'::' or ':::' import not declared from: ‘lifecycle’
```

I see that you used to use furrr in this `pvec()` function, which has now been deprecated
https://github.com/abjur/abjutils/blob/master/R/pvec.R

Since it has been deprecated for awhile, I think **the easiest solution would be for you to mark it as `.Defunct()`, and then remove all usage of furrr from the package, or to remove the function altogether.**

---

If you are not ready for that, then there are two things that I will need your help with:

1) This global override of `furrr::future_options()` is what causes the warning. https://github.com/abjur/abjutils/blob/cc3ec0c3474a4d29820e5dde4322799cdb0317b0/R/pvec.R#L91

   That function has now been soft deprecated in favor of `furrr::furrr_options()` (to free up that name for future to use if it wants to). Internally, my `future_options()` now calls a function from the lifecycle package. Since you have assigned my function directly into one of yours, R CMD Check found that you haven't Import-ed the lifecycle package, and it returned the above warning.

   Since you only Suggest furrr, the easiest thing to do here is probably to just set your `.options` argument to default to `NULL`, and inside `pvec()` you would call:

   ```
   if (is.null(.options)) {
     .options <- furrr::future_options()
   }
   ```

   Then you'd remove the override of `furrr:future_options()` on line 91.

2) This second point is optional, but would be good practice. Since you now only Suggest furrr, it is unsafe to have any function in your package that calls a `furrr::` function without first checking if furrr is installed. The easiest way to do that is to put this at the top of `pvec()`

   ```
   if (!rlang::is_installed("furrr")) stop("The furrr package must be installed to use this function")
   ```

**Comment by clente** [comment]
`pvec()` has been removed from the package and `abjutils` has been resubmitted to CRAN :+1: Thanks for the heads up
