### ISSUE TITLE
CPF mascarado

### ISSUE THREAD

**Issue by gabrielacaesar** [abjur/abjutils#18]
Oi, pessoal. Tudo bem?

Pesquisei aqui, mas não consegui descobrir. O pacote `abjutils` tem alguma função para pegar um CPF comum (`111.222.333-67`) ou (`11122233367`) e transformar em CPF mascarado (`***.222.333-**`)?

Obrigada!

**Comment by jtrecenti** [comment]
Não tem, @gabrielacaesar . O pacote abjutils foi feito para trabalhar com números de processos judiciais, então acho que trabalhar com CPF/CNPJ foge do escopo do pacote, infelizmente
