### ISSUE TITLE
Correct check_dig

### ISSUE THREAD

**Issue by jtrecenti** [abjur/abjutils#7]
This should i) clean the id, ii) check if it has 20 digits and iii) check if the digit is wright

ii) should raise a warning message and return `FALSE`. iii) should return `TRUE` or `FALSE`

```
abjutils::check_dig("0005268-75.2013.8.26.100")
```

**Comment by clente** [comment]
Fixed in 273de9c61935c740fc722f2017fc4513c391da1d
